#!/bin/bash
mdin=$1

[ $AMU_HOME ] || { echo "AMU_HOME not set. Exiting." ; exit ; }

[ "$mdin" ] || { echo "mdin file not supplied. Exiting." ; exit ; }

max=`find -L . -maxdepth 1 -type d | sed -e "s:^\./::" | sed -n "/^[0-9][0-9]*/p" | sort -n | tail -n 1`
step=$(( max + 1 ))
#echo "Creating step $step"
mkdir $step
cp $mdin $step/mdin
cd $step
$AMU_HOME/amu_setup

